version: '3'

services:

  mongo:
    build:
      context: ../../../../mongo
    volumes:
      - /opt/microservices/mongo:/data/db

  spring:
    build:
      context: ../../../
      dockerfile: src/main/docker/spring/Dockerfile.arm64v8
    ports:
      - 10009:8080
    depends_on:
      - mongo
    restart: always
