version: '3'
services:

  mongo:
    image: meks77/mongo
    restart: always
    volumes:
      - /opt/microservices/mongo:/data/db
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 1024M

  fastify:
    image: meks77/fastify-mongo
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 90M
    ports:
      - 3000

  go:
    image: meks77/go-mongo
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 20M
    ports:
      - 10005

  micronaut:
    image: meks77/micronaut-mongo
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 50M
    ports:
      - 8080

  quarkus:
    image: meks77/quarkus-mongo
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 50M
    ports:
      - 8080

  spring:
    image: meks77/spring-mongo
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
#          cpus: '1.0'
          memory: 100M
    ports:
      - 8080

#  wildfly:
#    image: meks77/wildfly-mongo
#    restart: always
#    depends_on:
#      - mongo
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 75M
#    ports:
#      - 8080
