FROM openjdk:12-alpine
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter
COPY *-runner.jar app.jar
CMD [ "java", "-jar", "app.jar" ]
EXPOSE 8080