version: '3'

services:

  couchdb:
    build:
      context: ../../../../couchdb/src/main/docker
    volumes:
      - /opt/microservices/couchdb/:/opt/couchdb/data/
#    ports:
#      - 5984:5984

  quarkus:
    build:
      context: ../../../
      dockerfile: src/main/docker/quarkus/Dockerfile.x86
    ports:
      - 10000:8080
    depends_on:
      - couchdb
    restart: always